### ISSUE TITLE
플러그인 적용 방법 질문

### ISSUE THREAD

**Issue by ghost** [itsss/MineMaze_II#1]
폴더 안의 모든 코드와 class 파일을 뜯어봐도 플레이어 위치 변경하거나 시간을 체크하고 메시지를 띄우는 명령줄만 있고, 외부로부터 뇌파 데이터 입력을 받아들이고 처리하는 명령줄이 안 보입니다. 뇌파 기기를 따로 구매한 후 이 플러그인을 적용해보려고 하는데요. 어떻게 설정을 해야 사용할 수 있나요?

**Comment by itsss** [comment]
안녕하세요. MineMaze II 개발자 강태원입니다. 말씀하신 대로 플러그인 내에는 뇌파인식 기능이 없습니다. 
플러그인 외 별도의 Python 스크립트가 OSC Streaming으로 받은 뇌파정보를 기반으로 
Windows의 키보드를 조작할 수 있도록 설계되어 있습니다.

**Comment by ghost** [comment]
그러면 그 파이썬 스크립트도 같이 공유해주실 수 있나요? 동생이랑 써보고 싶어서요.

**Comment by itsss** [comment]
사용하고 계시는 뇌파기기에 따라서 사용가능여부가 다릅니다. 
뇌파기기에 따라 Serial의 Input 방식이 다르고, 이를 별개로 설정해 주는 작업이 필요하게 됩니다.
이 repository는 Maker Faire 출품작의 오픈소스화와 2020 5월, 소프트웨어 물들다 행사의 일환으로 제가 제작한 마인크래프트 플러그인 소스코드를 공유드리기 위한 목적으로 개설된 것이기 때문에, 별도의 python 스크립트 공개계획은 없습니다.
더 궁금하신 사항이 있다면 itschool [at] itsc [dot] kr 로 연락주시면 자세히 답변드리도록 하겠습니다.
P.S. 프로그래밍 분야에 재능이 많으신 것으로 보이네요....!
감사합니다.

**Comment by ghost** [comment]
그럼 프로그램 구조가 어떻게 되어있는 건가요? 폰에서 데이터를 분석해서 컴퓨터에 신호를 전송하려면 안드로이드용 앱이 따로 필요했을텐데요. 어떤 모듈이나 소켓을 사용한 건가요?

**Comment by ghost** [comment]
사용영상을 보면 따로 연결선도 없었구요. 블루투스나 와이파이 연결을 사용한 건가요? Python으로 안드로이드에서 돌아가는 앱을 작성하셨다는데 그것도 좀 의아하구요. 집중도를 판단해서 움직인다고 나와있는데 사용한 수식이나 레퍼런스를 좀 공개해주실 수 있나요? 뇌파기기 데이터 출력으로부터 '집중도' 라는 변수를 추출할 수 있는 수식이요. 그 변수가 어느 값 이상일때 움직이게 만들었는지도 궁금하구요.

**Comment by ghost** [comment]
보통 깃허브에 프로그램을 공개할 때 시스템에서 가장 중요한 코어를 올리지 이렇게 점수계산이나 초기셋팅같은 지엽적인 내용만 들어있는 코드를 올리진 않습니다. 어떻게 셋팅했는지 설명해주시기 바랍니다.

**Comment by itsss** [comment]
안녕하세요. 강태원입니다.
말씀해주신 내용에 대해 답변드립니다.

1. 그럼 프로그램 구조가 어떻게 되어있는 건가요? 폰에서 데이터를 분석해서 컴퓨터에 신호를 전송하려면 안드로이드용 앱이 따로 필요했을텐데요. 어떤 모듈이나 소켓을 사용한 건가요?

-> OSC Streaming 기반으로 휴대폰-컴퓨터 간 통신이 이루어집니다.


2. 사용영상을 보면 따로 연결선도 없었구요. 블루투스나 와이파이 연결을 사용한 건가요? Python으로 안드로이드에서 돌아가는 앱을 작성하셨다는데 그것도 좀 의아하구요. 집중도를 판단해서 움직인다고 나와있는데 사용한 수식이나 레퍼런스를 좀 공개해주실 수 있나요? 뇌파기기 데이터 출력으로부터 '집중도' 라는 변수를 추출할 수 있는 수식이요. 그 변수가 어느 값 이상일때 움직이게 만들었는지도 궁금하구요.

-> 네. 와이파이 연결을 사용하여 OSC Streaming이 이루어집니다. Python에서 안드로이드에서 돌아가는 앱을 작성한 것은 아닙니다. 집중도를 판단하는 기준은 Python 스크립트에서 이루어집니다.


3. 보통 깃허브에 프로그램을 공개할 때 시스템에서 가장 중요한 코어를 올리지 이렇게 점수계산이나 초기셋팅같은 지엽적인 내용만 들어있는 코드를 올리진 않습니다. 어떻게 셋팅했는지 설명해주시기 바랍니다.

-> 위에 issue 답변을 참고해 주시기 바랍니다. 수식 부분도 마찬가지입니다. 그리고, 보통 GitHub에 issue를 올릴때 공손하게 올리지 이렇게 무례하게 issue를 올리지 않습니다. 다른 분들의 GitHub에 issue를 올릴 때도 마찬가지 입니다.

**Comment by ghost** [comment]
변명 잘 들었습니다. 감사합니다.

**Comment by ghost** [comment]
https://namu.wiki/w/%EC%86%A1%EC%9C%A0%EA%B7%BC%20%EB%85%BC%EB%AC%B8%20%ED%91%9C%EC%A0%88%20%EC%82%AC%EA%B1%B4#s-6

**Comment by itsss** [comment]
중학생인줄 알았는데... 대학생이시군요...!
그럼 즐거운 하루 보내세요.

강태원.

**Comment by ghost** [comment]
고등학생인데요.

**Comment by ghost** [comment]
그보다 대학생인 줄 알았는데 중학생이셨네요. 죄송합니다.
